/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rental;
import rental.Jrental;
import java.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import static rental.Jrental.*;
import javax.swing.JOptionPane;
/**
 *
 * @author A S U S
 */
public class hasil extends javax.swing.JFrame {

    /**
     * Creates new form hasil
     */
   
    public String nama1, no1, tp1, tk1, lp1, tkh1;
    public hasil(String val1, String val2, String val3, String val4, String val5, String val6) {
        initComponents();
        this.nama1 = val1;
        this.no1 = val2;
        this.tp1 = val3;
        this.tk1 = val4;
        this.lp1 = val5;
        this.tkh1 = val6;
        isinama();
        isino();
        isimrk();
        isitp();
        isitk();
        isilp();
        isihrg();
        isitkh();
        isidnd();
    }

    hasil(String nama1, String no1, String tp1, String tk1, String lp1, String tkh1, int bayar, String merk, int harga) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
    void isinama() {
        DefaultTableModel dt = (DefaultTableModel) tharga.getModel();
        Vector v = new Vector();
        v.add("NAMA");
        v.add(nama1);
        dt.addRow(v);
    }
    void isino() {
        DefaultTableModel dt = (DefaultTableModel) tharga.getModel();
        Vector v = new Vector();
        v.add("NO MOBIL");
        v.add(no1);
        dt.addRow(v);
    }
     
    void isimrk() {
        DefaultTableModel dt = (DefaultTableModel) tharga.getModel();
        Vector v = new Vector();
        v.add("MEREK ");
        v.add(merk);
        dt.addRow(v);
    }
    void isitp() {
        DefaultTableModel dt = (DefaultTableModel) tharga.getModel();
        Vector v = new Vector();
        v.add("TANGGAL PINJAM");
        v.add(tp1);
        dt.addRow(v);
    }
    void isitk() {
        DefaultTableModel dt = (DefaultTableModel) tharga.getModel();
        Vector v = new Vector();
        v.add("TANGGAL KEMBALI");
        v.add(tk1);
        dt.addRow(v);
    }
     void isilp() {
        DefaultTableModel dt = (DefaultTableModel) tharga.getModel();
        Vector v = new Vector();
        v.add("LAMA PINJAM");
        v.add(lp1+" Hari");
        dt.addRow(v);
    }
     void isihrg() {
        DefaultTableModel dt = (DefaultTableModel) tharga.getModel();
        Vector v = new Vector();
        v.add("HARGA");
        v.add("Rp "+harga+" /Hari");
        dt.addRow(v);
    }
     
     
    void isitkh() {
        DefaultTableModel dt = (DefaultTableModel) tharga.getModel();
        Vector v = new Vector();
        v.add("TELAT KEMBALI");
        v.add(tkh1+" HARI");
        dt.addRow(v);
    }
    void isidnd() {
        DefaultTableModel dt = (DefaultTableModel) tharga.getModel();
        Vector v = new Vector();
        v.add("BAYAR DENDA ");
        v.add("Rp "+bayar);
        dt.addRow(v);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tharga = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ha = new javax.swing.JLabel();
        kembali = new javax.swing.JButton();
        print = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        tharga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tharga.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tharga);
        if (tharga.getColumnModel().getColumnCount() > 0) {
            tharga.getColumnModel().getColumn(0).setResizable(false);
            tharga.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("KASIR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("TOTAL  :");

        ha.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        ha.setText("0");
        ha.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                haAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        kembali.setText("KEMBALI");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });

        print.setText("PRINT");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel3.setText("Rp");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(print)
                        .addGap(98, 98, 98)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ha, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(kembali))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(ha)
                    .addComponent(print))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kembali))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void haAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_haAncestorAdded
           
       ha.setText(String.valueOf(total)); 
        // TODO add your handling code here:
    }//GEN-LAST:event_haAncestorAdded

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "TERIMA KASIH ATAS KUNJUNGANYA !"
,"TERIMAKASIH", JOptionPane.PLAIN_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
 JOptionPane.showMessageDialog(this, "Fitur Untuk Penambahan Printer Device Belum Tersedia ! "
,"MAAF", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kembali;
    private javax.swing.JButton print;
    private javax.swing.JTable tharga;
    // End of variables declaration//GEN-END:variables
}
